import json
import discord
from discord.ext import commands
from discord import app_commands

# Initialize bot with required intents
intents = discord.Intents.default()
intents.guilds = True
intents.messages = True
intents.manage_roles = True
intents.manage_channels = True

bot = commands.Bot(command_prefix="!", intents=intents)

# Configuration - Replace with your actual Staff Dashboard URL
STAFF_DASHBOARD_URL = "https://your-staff-dashboard-url.vercel.app"

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} slash command(s).")
    except Exception as e:
        print(f"Failed to sync commands: {e}")

# -------------------------------------------------------------
# 1. NEW COMMAND: /dashboard (Server Admin Only)
# -------------------------------------------------------------
@bot.tree.command(name="dashboard", description="Sends the link to the Staff Dashboard (Admin Only).")
@app_commands.checks.has_permissions(administrator=True)
async def dashboard(interaction: discord.Interaction):
    embed = discord.Embed(
        title="🛠️ Staff Dashboard Access",
        description=f"Click the button below or use this link to access the staff dashboard:\n\n🔗 [Open Staff Dashboard]({STAFF_DASHBOARD_URL})",
        color=discord.Color.blue()
    )
    embed.set_footer(text="Confidential • Authorized Administrators Only")
    
    await interaction.response.send_message(embed=embed, ephemeral=True)

@dashboard.error
async def dashboard_error(interaction: discord.Interaction, error: app_commands.AppCommandError):
    if isinstance(error, app_commands.MissingPermissions):
        await interaction.response.send_message("❌ **Access Denied:** You must be a Server Administrator to use this command.", ephemeral=True)

# -------------------------------------------------------------
# 2. COMMAND: /build file: (Server Admin Only & Bot Admin Check)
# -------------------------------------------------------------
@bot.tree.command(name="build", description="Builds a Discord server structure using a blueprint JSON file.")
@app_commands.describe(file="Upload the server blueprint .json file generated by the client")
@app_commands.checks.has_permissions(administrator=True)
async def build(interaction: discord.Interaction, file: discord.Attachment):
    if not interaction.guild:
        await interaction.response.send_message("❌ This command can only be run inside a Discord server.", ephemeral=True)
        return

    guild = interaction.guild
    me = guild.me

    # Check if the bot has Administrator permissions
    if not me.guild_permissions.administrator:
        await interaction.response.send_message(
            "❌ **Permission Error:** Orca Bot requires **Administrator** permissions in this server to build roles and channels.",
            ephemeral=True
        )
        return

    await interaction.response.defer(thinking=True)

    if not file.filename.endswith('.json'):
        await interaction.followup.send("❌ Please attach a valid `.json` blueprint file.")
        return

    try:
        content = await file.read()
        data = json.loads(content.decode('utf-8'))
    except Exception as e:
        await interaction.followup.send(f"❌ Failed to parse JSON file: `{str(e)}`")
        return

    applied_separator = data.get("applied_separator", "│")
    roles_data = data.get("roles", [])
    categories_data = data.get("categories", [])

    created_roles = {}

    # Phase 1: Create Roles
    await interaction.followup.send("⏳ **Phase 1/2:** Creating server roles...")
    for role_info in roles_data:
        role_name = role_info.get("name", "New Role")
        hex_color = role_info.get("color", "#99aab5").lstrip('#')
        
        try:
            color_int = int(hex_color, 16)
        except ValueError:
            color_int = 0x99aab5

        existing_role = discord.utils.get(guild.roles, name=role_name)
        if existing_role:
            created_roles[role_name] = existing_role
        else:
            try:
                new_role = await guild.create_role(
                    name=role_name,
                    color=discord.Color(color_int),
                    reason="Orca Auto-Builder"
                )
                created_roles[role_name] = new_role
            except Exception as e:
                print(f"Failed to create role {role_name}: {e}")

    # Phase 2: Create Categories and Channels
    await interaction.followup.send("⏳ **Phase 2/2:** Creating categories and channels...")
    
    for cat_data in categories_data:
        cat_name = cat_data.get("name", "CATEGORY")
        if cat_data.get("icon"):
            cat_name = f"{cat_data.get('icon')} {cat_name}"

        category_overwrites = {}
        if cat_data.get("is_private", False):
            category_overwrites[guild.default_role] = discord.PermissionOverwrite(read_messages=False)

        category = await guild.create_category(
            name=cat_name,
            overwrites=category_overwrites,
            reason="Orca Auto-Builder"
        )

        for chan_data in cat_data.get("channels", []):
            emoji = chan_data.get("emoji", "💬")
            raw_name = chan_data.get("name", "channel")
            topic = chan_data.get("topic", "")
            is_private = chan_data.get("is_private", False)

            formatted_name = f"{emoji}{applied_separator}{raw_name}"

            channel_overwrites = {}
            if is_private:
                channel_overwrites[guild.default_role] = discord.PermissionOverwrite(read_messages=False)

            for role_info in roles_data:
                role_name = role_info.get("name")
                perms = role_info.get("permissions", {})
                if role_name in created_roles:
                    target_role = created_roles[role_name]
                    channel_overwrites[target_role] = discord.PermissionOverwrite(
                        read_messages=perms.get("view", True),
                        send_messages=perms.get("send", True),
                        manage_channels=perms.get("manage", False)
                    )

            await guild.create_text_channel(
                name=formatted_name,
                category=category,
                topic=topic,
                overwrites=channel_overwrites,
                reason="Orca Auto-Builder"
            )

    await interaction.followup.send("✅ **Server Construction Complete!** All roles, categories, channels, and permissions have been generated.")

BOT_TOKEN = "YOUR_DISCORD_BOT_TOKEN_HERE"

if __name__ == "__main__":
    bot.run(BOT_TOKEN)
