import discord
from discord import app_commands
from discord.ext import commands
import json

class OrcaBuilder(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    # ==========================================
    # 1. OWNER-ONLY NUKE COMMAND
    # ==========================================
    @app_commands.command(name="nuke", description="[OWNER ONLY] Deletes ALL server channels and leaves 1 #bot-commands channel.")
    async def nuke_server(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)

        guild = interaction.guild

        if interaction.user.id != guild.owner_id:
            await interaction.followup.send(
                "⛔ **Access Denied!** Only the server owner can execute this command.",
                ephemeral=True
            )
            return

        for channel in list(guild.channels):
            try:
                await channel.delete(reason="Server Nuke Command Executed by Owner")
            except Exception as e:
                print(f"Failed to delete channel {channel.name}: {e}")

        bot_channel = await guild.create_text_channel(
            name="bot-commands",
            topic="Control channel for executing bot commands and setup."
        )

        await bot_channel.send(
            f"💥 **Server Wiped by {interaction.user.mention}!**\n"
            f"All channels purged. You can now execute `/build` inside this channel."
        )

        await interaction.followup.send("✅ Server wiped cleanly! Created `#bot-commands`.", ephemeral=True)

    # ==========================================
    # 2. BUILD COMMAND (PURGES CHANNELS FIRST, THEN BUILDS)
    # ==========================================
    @app_commands.command(name="build", description="Deletes existing channels and builds layout from JSON blueprint.")
    @app_commands.describe(blueprint_json="JSON blueprint string generated by the Web Builder")
    async def build(self, interaction: discord.Interaction, blueprint_json: str):
        await interaction.response.defer(ephemeral=True)

        try:
            data = json.loads(blueprint_json)
        except json.JSONDecodeError:
            await interaction.followup.send("❌ Invalid JSON blueprint payload provided.", ephemeral=True)
            return

        target_guild_id = str(data.get("target_guild_id", "")).strip()
        current_guild_id = str(interaction.guild_id)

        # STRICT GUILD LOCKOUT VERIFICATION
        if target_guild_id != current_guild_id:
            await interaction.followup.send(
                f"⛔ **Guild Lockout Violation!** Blueprint is restricted to target server ID `{target_guild_id}`. "
                f"Cannot execute on current server ID `{current_guild_id}`.",
                ephemeral=True
            )
            return

        guild = interaction.guild

        # DELETE ALL EXISTING CHANNELS FIRST
        for channel in list(guild.channels):
            try:
                await channel.delete(reason="Wiping channels prior to applying layout blueprint.")
            except Exception as e:
                print(f"Could not delete {channel.name}: {e}")

        # CREATE ROLES
        role_map = {}
        for role_name in data.get("roles", []):
            existing = discord.utils.get(guild.roles, name=role_name)
            if not existing:
                try:
                    role_obj = await guild.create_role(name=role_name)
                    role_map[role_name] = role_obj
                except Exception as e:
                    print(f"Could not create role {role_name}: {e}")
            else:
                role_map[role_name] = existing

        # CONSTRUCT CATEGORIES & CHANNELS
        first_created_text_ch = None
        for cat_data in data.get("categories", []):
            category = await guild.create_category(cat_data.get("name", "CATEGORY"))
            
            for ch_data in cat_data.get("channels", []):
                ch_name = ch_data.get("name", "channel")
                ch_type = ch_data.get("type", "text")
                ch_topic = ch_data.get("topic", "")
                
                if ch_type == "voice":
                    await guild.create_voice_channel(name=ch_name, category=category)
                elif ch_type == "announcement":
                    try:
                        ann_ch = await guild.create_text_channel(name=ch_name, category=category, topic=ch_topic, news=True)
                        if not first_created_text_ch:
                            first_created_text_ch = ann_ch
                    except Exception:
                        text_ch = await guild.create_text_channel(name=ch_name, category=category, topic=ch_topic)
                        if not first_created_text_ch:
                            first_created_text_ch = text_ch
                else:
                    text_ch = await guild.create_text_channel(name=ch_name, category=category, topic=ch_topic)
                    if not first_created_text_ch:
                        first_created_text_ch = text_ch

        if first_created_text_ch:
            await first_created_text_ch.send(
                f"🎉 **Server Build Completed!**\n"
                f"Successfully constructed server architecture for **{data.get('server_name', 'Server')}**."
            )

        await interaction.followup.send(
            f"✅ Layout for **{data.get('server_name')}** deployed successfully!",
            ephemeral=True
        )

async def setup(bot: commands.Bot):
    await bot.add_cog(OrcaBuilder(bot))
